language: node_js
node_js:
  - 6
sudo: false
install:
  - npm install
  - npm run lint
script:
  - npm run build
deploy:
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./deploy.sh'
cache:
  directories:
    - node_modules
