language: node_js
node_js:
  - 6
sudo: false
install:
  - npm install
  - npm run lint
script:
  - npm run build
deploy:
  - '[ "x$TRAVIS_BRANCH" == "xmaster" ] && [ "x$TRAVIS_PULL_REQUEST" == "xfalse" ] && sh ./deploy.sh'
cache:
  directories:
  - node_modules
